apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdu-sensors.fullname" . }}
  labels:
    {{- include "pdu-sensors.labels" . | nindent 4 }}
data:
  {{- if .Values.telegrafSidecar.enabled }}
  telegraf.conf: |+
    [agent]
      interval = "{{ .Values.pduScrapeInterval }}s"
      round_interval = true
      logfile = ""
      omit_hostname = true

    [[inputs.prometheus]]
      urls = ["http://localhost:{{ .Values.metricsPort }}"]
      metric_version = 1

    [[outputs.influxdb]]
      urls = ["{{ default (include "call-subchart" (list . "influxdb" "influxdb.fullname") | printf "http://%s:8086") .Values.telegrafSidecar.influxdbUrl }}"]
      database = "{{ .Values.telegrafSidecar.influxdbDatabase }}"
      
    [[outputs.health]]
      service_address = "http://:8888"
      [[outputs.health.compares]]
        field = "buffer_size"
        lt = 5000.0
      [[outputs.health.contains]]
        field = "buffer_size"
    [[inputs.internal]]
      collect_memstats = false
  {{- end }}