apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: pdu-sensors

build:
  local:
    push: false
  artifacts:
  - image: registry.github.com/tanenbaum/raritan-pdu-exporter/exporter
    docker:
      dockerfile: build/exporter/Dockerfile
      buildArgs:
        GO_VERSION: "{{.GO_VERSION}}"
  tagPolicy:
    sha256: {}

deploy:
  helm:
    flags:
      install:
      - --atomic
    releases:
    - name: dev-exporter
      chartPath: ./deploy/charts/pdu-sensors
      imageStrategy:
        helm: {}
      artifactOverrides:
        image: registry.github.com/tanenbaum/raritan-pdu-exporter/exporter
      setValues:
        influxdb.enabled: true
        influxdb.persistence.enabled: false
        grafana.enabled: true
        telegrafSidecar.enabled: true
      setValueTemplates:
        pduUsername: "{{.PDU_USERNAME}}"
        pduPassword: "{{.PDU_PASSWORD}}"
        pduAddress: "{{.PDU_ADDRESS}}"